ci: add lint-staged

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,24 +1,8 @@
-# Check for formatting
-echo "🔎 Checking formatting...";
-pnpm format:check ||
+# Run lint-staged
+echo "🔎 Running lint-staged...";
+pnpm lint-staged ||
 (
-  echo "❌ Formatting errors detected. Please run 'pnpm format' and commit again.";
-  false;
-)
-
-# Check for linting
-echo "🔎 Checking linting...";
-pnpm lint:check ||
-(
-  echo "❌ Linting errors detected. Please run 'pnpm lint' and commit again.";
-  false;
-)
-
-# Check for type errors
-echo "🔎 Checking type errors...";
-pnpm typecheck ||
-(
-  echo "❌ Type errors detected. Please fix and commit again.";
+  echo "❌ Lint-staged errors detected. Please fix and commit again.";
   false;
 )
 
diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,8 +1,8 @@
-# Check for build errors
-echo "🔎 Checking build...";
-pnpm build ||
+# Check for type errors
+echo "🔎 Checking types...";
+pnpm typecheck ||
 (
-  echo "❌ Build errors detected. Please fix and commit again.";
+  echo "❌ Type errors detected. Please fix and commit again.";
   false;
 )
 
